---
abstract: 'Instant AJAX web front-end for DBIx::Class'
author:
  - 'Oliver Gorwits <oliver@cpan.org>'
build_requires:
  Catalyst: 0
  Catalyst::ScriptRunner: 0
  Class::Data::Inheritable: 0
  DBI: 0
  DBIx::Class: 0
  DBIx::Class::Schema: 0
  File::Temp: 0
  JSON::XS: 0
  Storable: 0
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-AutoCRUD
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Controller: 0
  Catalyst::Model: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Unicode::Encoding: 0
  Catalyst::Runtime: 5.70
  Catalyst::Utils: 0
  Catalyst::View::JSON: 0
  Catalyst::View::TT: 0
  DBD::SQLite: 0
  DBIx::Class: 0.08127
  DBIx::Class::Schema::Loader: 0
  Data::Dumper: 0
  Data::Page: 0
  Devel::InnerPackage: 0
  Exporter: 0
  File::Basename: 0
  File::Slurp: 0
  File::stat: 0
  JSON: 2.90
  Lingua::EN::Inflect::Number: 0
  List::MoreUtils: 0
  List::Util: 0
  MRO::Compat: 0
  SQL::Translator: 0
  SQL::Translator::Schema: 0
  SQL::Translator::Schema::Table: 0
  Scalar::Util: 0
  base: 0
  overload: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Catalyst-Plugin-AutoCRUD
  homepage: https://github.com/ollyg/Catalyst-Plugin-AutoCRUD/wiki
  repository: git://github.com/ollyg/Catalyst-Plugin-AutoCRUD.git
version: 2.142820
